# Generated by Django 3.2.10 on 2023-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
